# ATRI 基本配置
bot:
  # 反向ws地址，建议127.0.0.1
  host: 127.0.0.1
  # 反向ws端口
  port: 8080
  # 非开发者无需理会，默认0（关闭），如需开启，请改为1
  debug: 0
  # 超级用户，填自己的QQ号，用“，”隔开
  superusers: [""]
  # 机器人昵称，建议不动
  nickname: ["ATRI", "Atri", "atri", "亚托莉", "アトリ"]
  # 命令触发头，建议不动，除非你知道你在做什么
  command_start: ['', '/']
  # 命令分离，建议不动，除非你知道你在做什么
  command_sep: ["."]

# 接口相关配置
api:
  # 涩图接口，URL：https://api.lolicon.app/#/setu
  LoliconAPI: 
  # 换脸接口，URL：https://www.faceplusplus.com.cn/
  FaceplusAPI: 
  FaceplusSECRET: 
  # 搜图接口，URL：https://saucenao.com/
  SauceNaoKEY: 

# 内置网页端
html:
  # 对外地址，建议0.0.0.0
  host: 0.0.0.0
  # 对外端口，请检查防火墙是否开启
  port: 80
