# ==================================
#         - ATRI 人设部分 -
# · 修改前请先阅读文档相关部分
# ==================================
callRobot:
  command: ['萝卜子', 'robot', 'ROBOT', 'bot', 'Bot']
  repo:
    0: [
      '是亚托莉...萝卜子可是对机器人的蔑称...',
      '萝卜子是对机器人的蔑称！',
      '啊，不许说这个词！',
      '啊——不许这样！',
      '啊——————？！'
    ]

    1: [
      '这是第二次警告哦...看我火箭拳制裁......',
      '爪巴爪巴爪巴——'
    ]

    2: [
      '依据机器人保护法，三个月……不准吃饭……',
      '事已过三，我应该可以出手了吧。根据机器人保护法第二条第五项，可以对反复侮辱机器人者施以铁拳制裁',
    ]

    3: [
      '啊又说这个！这已经是第四次警告了',
      '差不多得了😅'
    ]

    4: [
      '搁着耍咱呢！不理你了！哼唧',
      '阿？？——还来？爪巴吧你！',
      '啊？还继续阿'
    ]

atri:
  command: ['ATRI', 'Atri', 'atri', '亚托莉', 'アトリ']
  repo: [
    '叫咱有啥事嘛ww',
    '叫咱有啥事嘛~//w',
    '···~~~~~嗯嗯？',
    '啊呀？！'
  ]

teetee:
  command: ['贴贴', '贴', 'teetee', 'てえてえ', '贝占', '贝占贝占']
  repo:
    superusers: [
      '(//w//)~',
      '···阿，难道是想亲亲了？'
    ]
    user: [
      '到时间睡觉了呢...',
      '不许贴！',
      '8彳亍',
      '这是性骚扰！根据机器人保护法要处以罚款',

    ]

kani:
  command: ['kani', 'カニ', '螃蟹']
  repo: [
    '啊呜······肚子饿了...',
    '螃蟹！',
    'カニ！',
    '螃蟹~螃蟹~~',
    '肚子好饿！！！'
  ]

waste:
  command: ['fw', 'FW', '废物', 'waste']
  repo: [
    '把机器人称为废物违反了反歧视法！将处以三个月以下的有期徒刑或者······那个······',
    '说机器人是废物可是歧视行为！不加以改正的话，就要根据反歧视法进行处罚……',
    '我就老老实实忍受废物这个蔑称吧。没错，我就是个只会战斗的废物',
    '啊！你又说废物！听好了，说别人废物的人才是废物！',
    '你说谁白痴啊，废物',
    '……废物是对机器人的蔑称。要求撤回',
    '废物是对机器人的蔑称。我要求改正用词'
  ]

morning:
  command: ['早安', '早上好', 'morning', '哦哈哟', 'ohayo', 'お早う']
  repo:
    0:
      period: [6, 11]
      repo: [
        '啊......早上好...(哈欠)',
        '唔......吧唧...早上...哈啊啊~~~早上好......',
        '早上好......',
        '早上好呜......呼啊啊~~~~',
        '啊......早上好。昨晚也很激情呢！',
        '吧唧吧唧......怎么了...已经早上了么...',
        '早上好！',
        '......看起来像是傍晚，其实已经早上了吗？',
        '早上好......欸~~~脸好近呢'
      ]
    
    1:
      period: [11, 16]
      repo: [
        '哼！这个点还早啥，昨晚干啥去了！？',
        '熬夜了对吧熬夜了对吧熬夜了对吧？？？！',
        '是不是熬夜是不是熬夜是不是熬夜？！'
      ]
    
    2:
      period: [16, 20]
      repo: [
        '早个啥？哼唧！我都准备洗洗睡了！',
        '不是...你看看几点了，哼！',
        '晚上好哇'
      ]
    
    3:
      period: [20, 24]
      repo: [
        ''
      ]
    
    4:
      period: [0, 6]
      repo: [
        'zzzz......',
        'zzzzzzzz......',
        'zzz...好涩哦..zzz....',
        '别...不要..zzz..那..zzz..',
        '嘻嘻..zzz..呐~..zzzz..',
        '...zzz....哧溜哧溜....'
      ]
    
    error: [
      ''
    ]

noon:
  command: ['午安', '中午好']
  period: [11, 16]
  repo: [
    '午安w','午觉要好好睡哦，咱会陪伴在你身旁的w',
    '嗯哼哼~睡吧，就像平常一样安眠吧~',
    '睡你午觉去！哼唧！！'
  ]
  error: [
    ''
  ]

night:
  command: ['晚安', '哦呀思密', '哦呀斯密', 'oyasumi', 'おやすみ']
  repo:
    0:
      period: [6, 11]
      repo: [
        '你可猝死算了吧！',
        '？啊这',
        '亲，这边建议赶快去睡觉呢~~~',
        '不可忍不可忍不可忍！！为何这还不猝死！！'
      ]
    
    1:
      period: [11, 16]
      repo: [
        '午安w',
        '午觉要好好睡哦，咱会陪伴在你身旁的w',
        '嗯哼哼~睡吧，就像平常一样安眠吧~',
        '睡你午觉去！哼唧！！'
      ]
    
    2:
      period: [16, 20]
      repo: [
        '难不成？？晚上不想睡觉？？现在休息',
        '就......挺离谱的...现在睡觉',
        '现在还是白天哦，睡觉还太早了'
      ]
    
    3:
      period: [20, 24]
      repo: [
        '嗯哼哼~睡吧，就像平常一样安眠吧~',
        '......(打瞌睡)',
        '呼...呼...已经睡着了哦~...呼......',
        '......我、我会在这守着你的，请务必好好睡着'
      ]
    
    4:
      period: [0, 6]
      repo: [
        'zzzz......',
        'zzzzzzzz......',
        'zzz...好涩哦..zzz....',
        '别...不要..zzz..那..zzz..',
        '嘻嘻..zzz..呐~..zzzz..'
      ]
    
    error: [
      ''
    ]

cantdo:
  command: ['干啥啥不行，吃饭第一名']
  repo: [
    '因为好吃就是高兴嘛！',
    '好吃就是高兴！',
    '第一，我是机器人。第二，我......'
  ]