hitokoto:
  command: ['一言']
  link: # 外部接口，详细请参考文档
    use: false
    url: ''
  local: # 本地库存，请勿做任何改动
    use: true
    file: ['a.json', 'b.json', 'c.json']
  times:
    3:
      repo: ['额......需要咱安慰一下嘛~？']
    6:
      repo: ['如果心里感到难受就赶快去睡觉奥！别再憋自己了！']