# ATRI 基本配置
version: YHN-00C-001
bot:
  # 反向ws地址，建议127.0.0.1
  host: 127.0.0.1
  # 反向ws端口
  port: 25565
  # 非开发者无需理会
  debug: 0
  # 超级用户，填自己的QQ号，用“，”隔开
  superusers: [1172294279]
  # 机器人昵称，建议不动
  nickname: ['ATRI', 'Atri', 'atri', '亚托莉', 'アトリ']
  # 命令触发头，建议不动，除非你知道你在做什么
  command_start: ['', '/']
  # 命令分离，建议不动，除非你知道你在做什么
  command_sep: ['.']
  # 会话失效时间，单位：分钟
  session_expire_timeout: 3
  # 会话延迟处理时间，单位：秒
  session_waiting_time: 3
  # 会话等待回复
  session_waiting_repo: [
    "歇歇8，。咱8能再快了",
    "太快惹，太快惹嗯",
    "你吼辣么快干什么！",
    "其实吧我觉得你这速度去d个vup挺适合",
    "我不接受！你太快了",
    "我有点担心，因为你太快了"
  ]

# # 接口相关配置
# api:
#   # 涩图接口，URL：https://api.lolicon.app/#/setu
#   lolicon: xxx
#   # 搜图接口，URL：https://saucenao.com/
#   SauceNaoKEY: xxx

# Post html，相关请参阅文档
http_post:
  # Post地址，建议127.0.0.1
  host: 127.0.0.1
  # Post端口，需同服务端 http 中的端口一致，而不是 ws
  port: 23333