setu:
  command: ['来张涩图', '涩图来', '开冲']
  link:
    url: 'https://api.lolicon.app/setu/'
    api_key: ''
    file: 'lolicon.db'
  local:
    normal: 'normal.db'
    near_r18: 'near_r18.db'
    r18: 'r18'
  repo:
    waiting: '别急，在找了！'